E_Ticaret.WebUI/Areas/admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Ticaret.Core.Entities;
using E_Ticaret.Data;
using E_Ticaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;

namespace E_Ticaret.WebUI.Areas.admin.Controllers
{
    [Area("Admin"), Authorize(Policy = "AdminPolicy")]
    public class NewsController : Controller
    {
        private readonly DatabaseContext _context;

        public NewsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: admin/News
        public async Task<IActionResult> Index()
        {
            return View(await _context.News.ToListAsync());
        }

        // GET: admin/News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: admin/News/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( News news, IFormFile? Image )
        {
            if (ModelState.IsValid)
            {
                news.Image = await FileHelper.FileLoaderAsync(Image, "/Img/News/");
                await _context.AddAsync(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: admin/News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,News news, IFormFile? Image, bool cbResmiSil = false)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (cbResmiSil)
                    {
                        news.Image = string.Empty;
                    }
                    if (Image is not null)
                        news.Image = await FileHelper.FileLoaderAsync(Image, "/Img/News/");

                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: admin/News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: admin/News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            if (news != null)
            {
                if (!string.IsNullOrEmpty(news.Image))
                {
                    FileHelper.FileRemover(news.Image, "/Img/News/");
                }
                _context.News.Remove(news);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.Id == id);
        }
    }
}

E_Ticaret.WebUI/Areas/admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Ticaret.Core.Entities;
using E_Ticaret.Data;
using E_Ticaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;

namespace E_Ticaret.WebUI.Areas.admin.Controllers
{
    [Area("Admin"), Authorize(Policy = "AdminPolicy")]
    public class ProductsController : Controller
    {
        private readonly DatabaseContext _context;

        public ProductsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: admin/Products
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Products.Include(p => p.Brand).Include(p => p.Category);
            return View(await databaseContext.ToListAsync());
        }

        // GET: admin/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: admin/Products/Create
        public IActionResult Create()
        {
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name");
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Product product, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                product.Image = await FileHelper.FileLoaderAsync(Image, "/Img/Products/");

                await _context.AddAsync(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", product.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: admin/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", product.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile? Image, bool cbResmiSil = false)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (cbResmiSil)
                    {
                        product.Image = string.Empty;
                    }
                    if (Image is not null)
                        product.Image = await FileHelper.FileLoaderAsync(Image, "/Img/Products/");

                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", product.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: admin/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                if (!string.IsNullOrEmpty(product.Image))
                {
                    FileHelper.FileRemover(product.Image, "/Img/Products/");
                }
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

E_Ticaret.WebUI/Areas/admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Ticaret.Core.Entities;
using E_Ticaret.Data;
using E_Ticaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;

namespace E_Ticaret.WebUI.Areas.admin.Controllers
{
    [Area("Admin"), Authorize(Policy = "AdminPolicy")]
    public class SlidersController : Controller
    {
        private readonly DatabaseContext _context;

        public SlidersController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: admin/Sliders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sliders.ToListAsync());
        }

        // GET: admin/Sliders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = await _context.Sliders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }

        // GET: admin/Sliders/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                slider.Image = await FileHelper.FileLoaderAsync(Image, "/Img/Sliders/");
                await _context.AddAsync(slider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }

        // GET: admin/Sliders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = await _context.Sliders.FindAsync(id);
            if (slider == null)
            {
                return NotFound();
            }
            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Slider slider, IFormFile? Image, bool cbResmiSil = false)
        {
            if (id != slider.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (cbResmiSil)
                    {
                        slider.Image = string.Empty;
                    }
                    if (Image is not null)
                        slider.Image = await FileHelper.FileLoaderAsync(Image, "/Img/Sliders/");

                    _context.Update(slider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SliderExists(slider.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }

        // GET: admin/Sliders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = await _context.Sliders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }

        // POST: admin/Sliders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var slider = await _context.Sliders.FindAsync(id);
            if (slider != null)
            {
                if (!string.IsNullOrEmpty(slider.Image))
                {
                    FileHelper.FileRemover(slider.Image, "/Img/Sliders/");
                }
                _context.Sliders.Remove(slider);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SliderExists(int id)
        {
            return _context.Sliders.Any(e => e.Id == id);
        }
    }
}

E_Ticaret.WebUI/Controllers/FavoritesController.cs
using E_Ticaret.Core.Entities;
using E_Ticaret.Data;
using E_Ticaret.Service.Abstract;
using E_Ticaret.WebUI.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;

namespace E_Ticaret.WebUI.Controllers
{
    public class FavoritesController : Controller
    {
        //private readonly DatabaseContext _context;

        //public FavoritesController(DatabaseContext context)
        //{
        //    _context = context;
        //}
        private readonly IService<Product> _service;

        public FavoritesController(IService<Product> service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var favoriler = GetFavorites();
            return View(favoriler);
        }

        private List<Product> GetFavorites()
        {
            return HttpContext.Session.GetJson<List<Product>>("GetFavorites") ?? [];
        }

        public IActionResult Add(int ProductId)
        {
            var favoriler = GetFavorites();
            //var product = _context.Products.Find(ProductId); // Databasede ki ilgili ıd ye sahip productı bul.
            var product = _service.Find(ProductId); // Databasede ki ilgili ıd ye sahip productı bul.

            if (product != null && !favoriler.Any(p => p.Id == ProductId)) // product null değilse ve favorilerde bu productıd ye sahip ürün yoksa bu koşula girer ve burada favorilere ekleriz.
            {
                favoriler.Add(product);
                HttpContext.Session.SetJson("GetFavorites", favoriler); // favorileri (value) json tipine dönüştürür
            }

            return RedirectToAction("Index");
        }

        public IActionResult Remove(int ProductId)
        {
            var favoriler = GetFavorites();
            // var product = _context.Products.Find(ProductId);
            var product = _service.Find(ProductId);
            if (product != null && favoriler.Any(p => p.Id == ProductId))
            {
                favoriler.RemoveAll(i => i.Id == product.Id);
                HttpContext.Session.SetJson("GetFavorites", favoriler);
            }
            return RedirectToAction("Index");

        }
    }
}

E_Ticaret.WebUI/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Ticaret.WebUI</title>
    <script type="importmap"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Ticaret.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body>
    <div class="container">
        @Html.Raw(TempData["Message"])
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" ></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

E_Ticaret.WebUI/Views/Shared/_Footer.cshtml
<section class="bg-light">
    <div class="container">
        <footer class="py-5">
            <div class="row">
                <div class="col-6 col-md-3 mb-3">
                    <h5>Bize Ulaşın</h5>
                    <div class="col-auto">
                        <div>
                            <h6>Adres</h6>
                            Göztepe / Kadıköy / İstanbul
                        </div>
                        <div>
                            <h6>Email</h6>
                            info@eticaretsitesi.com
                        </div>
                        <div>
                            <h6>Telefon</h6>
                            0216 444 25 18
                        </div>
                    </div>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Çok Satan Markalar</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Monster</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Asus</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Acer</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Excalibur</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Samsung</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-3 mb-3">
                    <h5>Çok Satan Kategoriler</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Dizüstü Bilgisayar</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Masaüstü Bilgisayar</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Tablet Bilgisayar</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Monitörler</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">TV & Görüntü & Ses Sistemleri</a></li>
                    </ul>
                </div>

                <div class="col-md-4 mb-3">
                    <form>
                        <h5>E Bültene Abone Olun</h5>
                        <p>Kampanyalardan önce sizin haberiniz olsun.</p>
                        <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                            <label for="newsletter1" class="visually-hidden">Email</label>
                            <input id="newsletter1" type="text" class="form-control" placeholder="Email">
                            <button class="btn btn-primary text-nowrap" type="button">Abone Ol</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p>© 2024 Eticaret, Ltd. Tüm hakları saklıdır.</p>
                <ul class="list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-secondary" href="https://x.com/?lang=" target="_blank">
                            <i class="bi bi-twitter-x"></i>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-secondary" href="https://www.instagram.com/accounts/login/" target="_blank">
                            <i class="bi bi-instagram"></i>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-secondary" href="https://www.facebook.com/?locale=tr_TR" target="_blank">
                            <i class="bi bi-facebook"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>
</section>

E_Ticaret.WebUI/Views/Shared/_Header.cshtml
@using E_Ticaret.WebUI.ExtensionMethods

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Ticaret.WebUI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-evenly">


                <ul class="navbar-nav m-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Anasayfa</a>
                    </li>
                    @await Component.InvokeAsync("Categories")
                </ul>
                <form action="/Products" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                    <input name="q" type="search" class="form-control" placeholder="Ürün Ara..." aria-label="Search">
                </form>


                @* Buradaki user .netin içerisinde bulunan kullanıcı işlemlerini takip edebilmek için bulunan user 
                     bizim oluşturduğumuz user değil. Bu oturum açmış bir kullanıcı olup olmadığına bakar. Kullanıcı 
                     sisteme authentice olmuşmu buna bakar *@


                @if (Context.User.Identity.IsAuthenticated)
                {
                    <div class="dropdown">
                        <a class="dropdown-toggle nav-link text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-fill"></i> Hesabım
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/Account">Kullanıcı Bilgilerim</a></li>
                            <li><a class="dropdown-item" href="/MyAddresses/Index">Kayıtlı Adreslerim</a></li>
                            <li><a class="dropdown-item" href="/Account/MyOrders">Siparişlerim</a></li>
                            <li><a class="dropdown-item" href="/Account">Değerlendirmelerim</a></li>
                            <li class="text-center"><a class=" btn btn-danger" href="/Account/SignOut">Oturumu Kapat</a></li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="dropdown">
                        <a class="dropdown-toggle nav-link text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person"></i> Giriş Yap
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/Account/SignIn">Giriş</a></li>
                            <li><a class="dropdown-item" href="/Account/SignUp">Üye Ol</a></li>
                        </ul>
                    </div>
                }


                <div class="dropdown mx-3">
                    <a class="nav-link text-dark" href="/Favorites">
                        @{
                            var favorites = Context.Session.GetJson<List<Product>>("GetFavorites");
                            if (favorites is not null && favorites.Count > 0)
                            {
                                <i class="bi bi-heart-fill"></i> @:Favorilerim (@favorites.Count)
                            }
                            else
                            {
                                <i class="bi bi-heart"></i> @:Favorilerim
                            }
                        }
                    </a>
                </div>

            <div class="dropdown me-3">
                    @{
                        var cart = Context.Session.GetJson<E_Ticaret.Service.Concrete.CartService>("Cart");
                        if (cart != null && cart.CartLines.Count > 0)
                        {
                        <a class="dropdown-toggle nav-link text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-cart-fill"></i> Sepetim
                            <span class="badge bg-danger text-white ms-1 rounded-pill">
                                    @cart.CartLines.Count
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                                @foreach (var item in cart.CartLines)
                                {
                                <li>
                                    <a class="dropdown-item" href="/Products/Details/@item.Product.Id">
                                        <img src="/Img/Products/@item.Product.Image" alt="" height="40" />
                                            @item.Product.Name
                                    </a>
                                </li>
                                }
                            <li class="text-center"><a class="btn btn-warning m-auto" href="/Cart">Sepete Git</a></li>
                        </ul>
                        }
                        else
                        {
                        <a class="nav-link text-dark" href="/Cart">
                            <i class="bi bi-cart"></i> Sepetim
                        </a>
                        }
                    }
            </div>


            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">İletişim</a>


        </div>
        </div>
    </nav>
</header>

E_Ticaret.WebUI/Views/Shared/_NewsView.cshtml
@model News

<div class="col mb-5">
    <a href="/News/Details/@Model.Id">
        <img src="/Img/News/@Model.Image" alt="@Model.Name" class="img-fluid" />
    </a>
</div>

E_Ticaret.WebUI/Views/Shared/_ProductView.cshtml
@model Product

<div class="col mb-5">
    <div class="card h-100">
        <!-- Sale badge-->
        <div class="badge position-absolute" style="top: 0.5rem; right: 0.5rem">
            <form asp-action="Add" asp-controller="Favorites">
                <input type="hidden" name="ProductId" value="@Model.Id" />
                <button class="btn btn-transparent" type="submit" style="box-shadow: none">
                    <i class="bi bi-heart"></i>
                </button>
            </form>
        </div>
        <!-- Product image-->
        <a href="/Products/Details/@Model.Id">
            <img class="card-img-top" src="~/Img/Products/@Model.Image" alt="@Model.Name">
        </a>
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">@Model.Name</h5>
                <!-- Product price-->
                @Model.Price.ToString("c")
            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="d-flex justify-content-between w-100">
                <form action="/Cart/Add" method="post">
                    <input type="hidden" name="ProductId" value="@Model.Id" />
                    <div class="text-center">
                        <button class="btn btn-outline-dark mt-auto" type="submit">
                            <i class="bi-cart-fill me-1"></i> Sepete Ekle
                        </button>
                    </div>
                </form>
                <form action="/Favorites/Add" method="post">
                    <input type="hidden" name="ProductId" value="@Model.Id" />
                    <div class="text-center">
                        <button class="btn btn-outline-dark mt-auto" type="submit">
                            <i class="bi-heart-fill me-1"></i>
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>